//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteKei.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteKei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About_CheckOutOnGithub.
        /// </summary>
        public static string About_CheckOutOnGithub {
            get {
                return ResourceManager.GetString("About_CheckOutOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonText_Cancel.
        /// </summary>
        public static string ButtonText_Cancel {
            get {
                return ResourceManager.GetString("ButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonText_Create.
        /// </summary>
        public static string ButtonText_Create {
            get {
                return ResourceManager.GetString("ButtonText_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonText_Execute.
        /// </summary>
        public static string ButtonText_Execute {
            get {
                return ResourceManager.GetString("ButtonText_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_CloseDatabase.
        /// </summary>
        public static string ContextMenuItem_CloseDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_CloseDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteDatabase.
        /// </summary>
        public static string ContextMenuItem_DeleteDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteTable.
        /// </summary>
        public static string ContextMenuItem_DeleteTable {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteTrigger.
        /// </summary>
        public static string ContextMenuItem_DeleteTrigger {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_DeleteView.
        /// </summary>
        public static string ContextMenuItem_DeleteView {
            get {
                return ResourceManager.GetString("ContextMenuItem_DeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_EmptyTable.
        /// </summary>
        public static string ContextMenuItem_EmptyTable {
            get {
                return ResourceManager.GetString("ContextMenuItem_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_NewDatabase.
        /// </summary>
        public static string ContextMenuItem_NewDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_NewTable.
        /// </summary>
        public static string ContextMenuItem_NewTable {
            get {
                return ResourceManager.GetString("ContextMenuItem_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_OpenDatabase.
        /// </summary>
        public static string ContextMenuItem_OpenDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_OpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextMenuItem_RenameDatabase.
        /// </summary>
        public static string ContextMenuItem_RenameDatabase {
            get {
                return ResourceManager.GetString("ContextMenuItem_RenameDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_DatabaseName.
        /// </summary>
        public static string DatabaseGeneralTab_DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_DatabasePath.
        /// </summary>
        public static string DatabaseGeneralTab_DatabasePath {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_NoTablesFound.
        /// </summary>
        public static string DatabaseGeneralTab_NoTablesFound {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_NoTablesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_Records.
        /// </summary>
        public static string DatabaseGeneralTab_Records {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_TableColumns.
        /// </summary>
        public static string DatabaseGeneralTab_TableColumns {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_TableName.
        /// </summary>
        public static string DatabaseGeneralTab_TableName {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_TableRecords.
        /// </summary>
        public static string DatabaseGeneralTab_TableRecords {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_TableRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseGeneralTab_Tables.
        /// </summary>
        public static string DatabaseGeneralTab_Tables {
            get {
                return ResourceManager.GetString("DatabaseGeneralTab_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_About.
        /// </summary>
        public static string MenuItemHeader_About {
            get {
                return ResourceManager.GetString("MenuItemHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Documentation.
        /// </summary>
        public static string MenuItemHeader_Documentation {
            get {
                return ResourceManager.GetString("MenuItemHeader_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Exit.
        /// </summary>
        public static string MenuItemHeader_Exit {
            get {
                return ResourceManager.GetString("MenuItemHeader_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_File.
        /// </summary>
        public static string MenuItemHeader_File {
            get {
                return ResourceManager.GetString("MenuItemHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Help.
        /// </summary>
        public static string MenuItemHeader_Help {
            get {
                return ResourceManager.GetString("MenuItemHeader_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_NewDatabase.
        /// </summary>
        public static string MenuItemHeader_NewDatabase {
            get {
                return ResourceManager.GetString("MenuItemHeader_NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_OpenDatabase.
        /// </summary>
        public static string MenuItemHeader_OpenDatabase {
            get {
                return ResourceManager.GetString("MenuItemHeader_OpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Preferences.
        /// </summary>
        public static string MenuItemHeader_Preferences {
            get {
                return ResourceManager.GetString("MenuItemHeader_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_QueryEditor.
        /// </summary>
        public static string MenuItemHeader_QueryEditor {
            get {
                return ResourceManager.GetString("MenuItemHeader_QueryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItemHeader_Tools.
        /// </summary>
        public static string MenuItemHeader_Tools {
            get {
                return ResourceManager.GetString("MenuItemHeader_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_DatabaseDeleteWarning.
        /// </summary>
        public static string MessageBox_DatabaseDeleteWarning {
            get {
                return ResourceManager.GetString("MessageBox_DatabaseDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_EmptyTable.
        /// </summary>
        public static string MessageBox_EmptyTable {
            get {
                return ResourceManager.GetString("MessageBox_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBox_TableDeleteWarning.
        /// </summary>
        public static string MessageBox_TableDeleteWarning {
            get {
                return ResourceManager.GetString("MessageBox_TableDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessaxeBoxTitle_DatabaseDeletion.
        /// </summary>
        public static string MessageBoxTitle_DatabaseDeletion {
            get {
                return ResourceManager.GetString("MessageBoxTitle_DatabaseDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_EmptyTable.
        /// </summary>
        public static string MessageBoxTitle_EmptyTable {
            get {
                return ResourceManager.GetString("MessageBoxTitle_EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBoxTitle_TableDeletion.
        /// </summary>
        public static string MessageBoxTitle_TableDeletion {
            get {
                return ResourceManager.GetString("MessageBoxTitle_TableDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryEditor_Label_Database.
        /// </summary>
        public static string QueryEditor_Label_Database {
            get {
                return ResourceManager.GetString("QueryEditor_Label_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabContent_GroupBoxHeader_About.
        /// </summary>
        public static string TabContent_GroupBoxHeader_About {
            get {
                return ResourceManager.GetString("TabContent_GroupBoxHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabContent_GroupBoxHeader_Columns.
        /// </summary>
        public static string TabContent_GroupBoxHeader_Columns {
            get {
                return ResourceManager.GetString("TabContent_GroupBoxHeader_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabContent_GroupBoxHeader_Columns.
        /// </summary>
        public static string TabContent_GroupBoxHeader_Tables {
            get {
                return ResourceManager.GetString("TabContent_GroupBoxHeader_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_General.
        /// </summary>
        public static string TabHeader_General {
            get {
                return ResourceManager.GetString("TabHeader_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_GeneralTable.
        /// </summary>
        public static string TabHeader_GeneralTable {
            get {
                return ResourceManager.GetString("TabHeader_GeneralTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabHeader_TableRecords.
        /// </summary>
        public static string TabHeader_TableRecords {
            get {
                return ResourceManager.GetString("TabHeader_TableRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_ButtonText_AddColumn.
        /// </summary>
        public static string TableCreator_ButtonText_AddColumn {
            get {
                return ResourceManager.GetString("TableCreator_ButtonText_AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_Label_Database.
        /// </summary>
        public static string TableCreator_Label_Database {
            get {
                return ResourceManager.GetString("TableCreator_Label_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_Label_TableName.
        /// </summary>
        public static string TableCreator_Label_Default {
            get {
                return ResourceManager.GetString("TableCreator_Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_Label_TableName.
        /// </summary>
        public static string TableCreator_Label_TableName {
            get {
                return ResourceManager.GetString("TableCreator_Label_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_NoDatabaseSelected.
        /// </summary>
        public static string TableCreator_NoDatabaseSelected {
            get {
                return ResourceManager.GetString("TableCreator_NoDatabaseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_TabHeader_Columns.
        /// </summary>
        public static string TableCreator_TabHeader_Columns {
            get {
                return ResourceManager.GetString("TableCreator_TabHeader_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCreator_TableCreateSuccess.
        /// </summary>
        public static string TableCreator_TableCreateSuccess {
            get {
                return ResourceManager.GetString("TableCreator_TableCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_ButtonText_Empty.
        /// </summary>
        public static string TableGeneralTab_ButtonText_Empty {
            get {
                return ResourceManager.GetString("TableGeneralTab_ButtonText_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_ColumnName.
        /// </summary>
        public static string TableGeneralTab_ColumnName {
            get {
                return ResourceManager.GetString("TableGeneralTab_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_Columns.
        /// </summary>
        public static string TableGeneralTab_Columns {
            get {
                return ResourceManager.GetString("TableGeneralTab_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_DataType.
        /// </summary>
        public static string TableGeneralTab_DataType {
            get {
                return ResourceManager.GetString("TableGeneralTab_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_Default.
        /// </summary>
        public static string TableGeneralTab_Default {
            get {
                return ResourceManager.GetString("TableGeneralTab_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_NoColumnsFound.
        /// </summary>
        public static string TableGeneralTab_NoColumnsFound {
            get {
                return ResourceManager.GetString("TableGeneralTab_NoColumnsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_Records.
        /// </summary>
        public static string TableGeneralTab_Records {
            get {
                return ResourceManager.GetString("TableGeneralTab_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_TableCreateStatement.
        /// </summary>
        public static string TableGeneralTab_TableCreateStatement {
            get {
                return ResourceManager.GetString("TableGeneralTab_TableCreateStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableGeneralTab_TableName.
        /// </summary>
        public static string TableGeneralTab_TableName {
            get {
                return ResourceManager.GetString("TableGeneralTab_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_CloseDatabase.
        /// </summary>
        public static string Tooltip_CloseDatabase {
            get {
                return ResourceManager.GetString("Tooltip_CloseDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_DeleteDatabase.
        /// </summary>
        public static string Tooltip_DeleteDatabase {
            get {
                return ResourceManager.GetString("Tooltip_DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_NewDatabase.
        /// </summary>
        public static string Tooltip_NewDatabase {
            get {
                return ResourceManager.GetString("Tooltip_NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_OpenDatabase.
        /// </summary>
        public static string Tooltip_OpenDatabase {
            get {
                return ResourceManager.GetString("Tooltip_OpenDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip_WriteSQLStatement.
        /// </summary>
        public static string Tooltip_WriteSQLStatement {
            get {
                return ResourceManager.GetString("Tooltip_WriteSQLStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_About.
        /// </summary>
        public static string WindowTitle_About {
            get {
                return ResourceManager.GetString("WindowTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_QueryEditor.
        /// </summary>
        public static string WindowTitle_QueryEditor {
            get {
                return ResourceManager.GetString("WindowTitle_QueryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_SelectQueryCreator.
        /// </summary>
        public static string WindowTitle_SelectQueryCreator {
            get {
                return ResourceManager.GetString("WindowTitle_SelectQueryCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle_TableCreator.
        /// </summary>
        public static string WindowTitle_TableCreator {
            get {
                return ResourceManager.GetString("WindowTitle_TableCreator", resourceCulture);
            }
        }
    }
}
